### ISSUE TITLE
Fixear timezone en el mensaje

### ISSUE THREAD

**Issue by pablotejimenez** [leiteszeke/extendeal-slackbot#1]
Se requiere arreglar el timezone que toma el texto.

* Está en UTC 0 en vez de -3.
* Además hay una diferencia de +/- 1 minuto entre la hora en que se dispara el bot y la hora dentro del texto.

:cop_parrot:

**Comment by leiteszeke** [comment]
Resolved in v1.0.1
Version released 2018/11/30 @ 11:32

**Comment by leiteszeke** [comment]
@pablotejimenez difference between message time and slack time is a Slack API problem. We can't handle correctly. Sorry :sad_parrot:
